apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: prometheus-nvidia-exporter
  namespace: monitoring
  labels:
      app: prometheus
      component: nvidia-exporter
spec:
  template:
    metadata:
      name: prometheus-nvidia-exporter
      labels:
        app: prometheus
        component: nvidia-exporter
    spec:
      volumes:
      - name: nvidialib
        hostPath:
          path: /var/lib/nvidia-docker/volumes/nvidia_driver/375.66
      containers:
        - name: prometheus-nvidia-exporter
          image: yujioshima/nv-porter
          imagePullPolicy: Always
          volumeMounts:
          - mountPath: /usr/local/nvidia
            name: nvidialib
          securityContext:
            privileged: true
          lifecycle:
            preStop:
              exec:
                command: ["--web.listen-address", "0.0.0.0:9114"]
          ports:
          - name: prom-nv-exp
            containerPort: 9114
            hostPort: 9114 
      hostNetwork: true
      hostPID: true
